# lists all tokens that are key words in the SQL standard and in PostgreSQL 10.4.
# run command in psql and paste the result:
# SELECT pg_get_keywords;
pg = [
 'abort,U,unreserved',
 'absolute,U,unreserved',
 'access,U,unreserved',
 'action,U,unreserved',
 'add,U,unreserved',
 'admin,U,unreserved',
 'after,U,unreserved',
 'aggregate,U,unreserved',
 'all,R,reserved',
 'also,U,unreserved',
 'alter,U,unreserved',
 'always,U,unreserved',
 'analyse,R,reserved',
 'analyze,R,reserved',
 'and,R,reserved',
 'any,R,reserved',
 'array,R,reserved',
 'as,R,reserved',
 'asc,R,reserved',
 'assertion,U,unreserved',
 'assignment,U,unreserved',
 'asymmetric,R,reserved',
 'at,U,unreserved',
 'attach,U,unreserved',
 'attribute,U,unreserved',
 'authorization,T,"reserved can be function or type name"',
 'backward,U,unreserved',
 'before,U,unreserved',
 'begin,U,unreserved',
 'between,C,"unreserved cannot be function or type name"',
 'bigint,C,"unreserved cannot be function or type name"',
 'binary,T,"reserved can be function or type name"',
 'bit,C,"unreserved cannot be function or type name"',
 'boolean,C,"unreserved cannot be function or type name"',
 'both,R,reserved',
 'by,U,unreserved',
 'cache,U,unreserved',
 'called,U,unreserved',
 'cascade,U,unreserved',
 'cascaded,U,unreserved',
 'case,R,reserved',
 'cast,R,reserved',
 'catalog,U,unreserved',
 'chain,U,unreserved',
 'char,C,"unreserved cannot be function or type name"',
 'character,C,"unreserved cannot be function or type name"',
 'characteristics,U,unreserved',
 'check,R,reserved',
 'checkpoint,U,unreserved',
 'class,U,unreserved',
 'close,U,unreserved',
 'cluster,U,unreserved',
 'coalesce,C,"unreserved cannot be function or type name"',
 'collate,R,reserved',
 'collation,T,"reserved can be function or type name"',
 'column,R,reserved',
 'columns,U,unreserved',
 'comment,U,unreserved',
 'comments,U,unreserved',
 'commit,U,unreserved',
 'committed,U,unreserved',
 'concurrently,T,"reserved can be function or type name"',
 'configuration,U,unreserved',
 'conflict,U,unreserved',
 'connection,U,unreserved',
 'constraint,R,reserved',
 'constraints,U,unreserved',
 'content,U,unreserved',
 'continue,U,unreserved',
 'conversion,U,unreserved',
 'copy,U,unreserved',
 'cost,U,unreserved',
 'create,R,reserved',
 'cross,T,"reserved can be function or type name"',
 'csv,U,unreserved',
 'cube,U,unreserved',
 'current,U,unreserved',
 'current_catalog,R,reserved',
 'current_date,R,reserved',
 'current_role,R,reserved',
 'current_schema,T,"reserved can be function or type name"',
 'current_time,R,reserved',
 'current_timestamp,R,reserved',
 'current_user,R,reserved',
 'cursor,U,unreserved',
 'cycle,U,unreserved',
 'data,U,unreserved',
 'database,U,unreserved',
 'day,U,unreserved',
 'deallocate,U,unreserved',
 'dec,C,"unreserved cannot be function or type name"',
 'decimal,C,"unreserved cannot be function or type name"',
 'declare,U,unreserved',
 'default,R,reserved',
 'defaults,U,unreserved',
 'deferrable,R,reserved',
 'deferred,U,unreserved',
 'definer,U,unreserved',
 'delete,U,unreserved',
 'delimiter,U,unreserved',
 'delimiters,U,unreserved',
 'depends,U,unreserved',
 'desc,R,reserved',
 'detach,U,unreserved',
 'dictionary,U,unreserved',
 'disable,U,unreserved',
 'discard,U,unreserved',
 'distinct,R,reserved',
 'do,R,reserved',
 'document,U,unreserved',
 'domain,U,unreserved',
 'double,U,unreserved',
 'drop,U,unreserved',
 'each,U,unreserved',
 'else,R,reserved',
 'enable,U,unreserved',
 'encoding,U,unreserved',
 'encrypted,U,unreserved',
 'end,R,reserved',
 'enum,U,unreserved',
 'escape,U,unreserved',
 'event,U,unreserved',
 'except,R,reserved',
 'exclude,U,unreserved',
 'excluding,U,unreserved',
 'exclusive,U,unreserved',
 'execute,U,unreserved',
 'exists,C,"unreserved cannot be function or type name"',
 'explain,U,unreserved',
 'extension,U,unreserved',
 'external,U,unreserved',
 'extract,C,"unreserved cannot be function or type name"',
 'false,R,reserved',
 'family,U,unreserved',
 'fetch,R,reserved',
 'filter,U,unreserved',
 'first,U,unreserved',
 'float,C,"unreserved cannot be function or type name"',
 'following,U,unreserved',
 'for,R,reserved',
 'force,U,unreserved',
 'foreign,R,reserved',
 'forward,U,unreserved',
 'freeze,T,"reserved can be function or type name"',
 'from,R,reserved',
 'full,T,"reserved can be function or type name"',
 'function,U,unreserved',
 'functions,U,unreserved',
 'generated,U,unreserved',
 'global,U,unreserved',
 'grant,R,reserved',
 'granted,U,unreserved',
 'greatest,C,"unreserved cannot be function or type name"',
 'group,R,reserved',
 'grouping,C,"unreserved cannot be function or type name"',
 'handler,U,unreserved',
 'having,R,reserved',
 'header,U,unreserved',
 'hold,U,unreserved',
 'hour,U,unreserved',
 'identity,U,unreserved',
 'if,U,unreserved',
 'ilike,T,"reserved can be function or type name"',
 'immediate,U,unreserved',
 'immutable,U,unreserved',
 'implicit,U,unreserved',
 'import,U,unreserved',
 'in,R,reserved',
 'including,U,unreserved',
 'increment,U,unreserved',
 'index,U,unreserved',
 'indexes,U,unreserved',
 'inherit,U,unreserved',
 'inherits,U,unreserved',
 'initially,R,reserved',
 'inline,U,unreserved',
 'inner,T,"reserved can be function or type name"',
 'inout,C,"unreserved cannot be function or type name"',
 'input,U,unreserved',
 'insensitive,U,unreserved',
 'insert,U,unreserved',
 'instead,U,unreserved',
 'int,C,"unreserved cannot be function or type name"',
 'integer,C,"unreserved cannot be function or type name"',
 'intersect,R,reserved',
 'interval,C,"unreserved cannot be function or type name"',
 'into,R,reserved',
 'invoker,U,unreserved',
 'is,T,"reserved can be function or type name"',
 'isnull,T,"reserved can be function or type name"',
 'isolation,U,unreserved',
 'join,T,"reserved can be function or type name"',
 'key,U,unreserved',
 'label,U,unreserved',
 'language,U,unreserved',
 'large,U,unreserved',
 'last,U,unreserved',
 'lateral,R,reserved',
 'leading,R,reserved',
 'leakproof,U,unreserved'
]